# Configuration for vim-alchemy builds
# Ensures rug dependency (GMP/MPFR) is compiled with gnu17

[env]
# Set global CFLAGS for all builds
CFLAGS = "-std=gnu17"
CXXFLAGS = "-std=gnu++17"

[target.x86_64-unknown-linux-gnu]
# No special configuration needed for native Linux x64

[target.aarch64-unknown-linux-gnu]
linker = "aarch64-linux-gnu-gcc"

[target.x86_64-apple-darwin]
# macOS Intel - clang uses -std=gnu17 syntax

[target.aarch64-apple-darwin]
# macOS Apple Silicon - clang uses -std=gnu17 syntax

# Windows targets are not supported due to rug dependency on GMP/MPFR

# Cross-compilation environment variables
[target.'cfg(target_arch = "aarch64")'.env]
CC_aarch64_unknown_linux_gnu = "aarch64-linux-gnu-gcc"
CXX_aarch64_unknown_linux_gnu = "aarch64-linux-gnu-g++"
AR_aarch64_unknown_linux_gnu = "aarch64-linux-gnu-ar"