name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g., v0.1.0)'
        required: true
        default: 'v0.1.0'
      prerelease:
        description: 'Is this a prerelease?'
        type: boolean
        required: true
        default: true

env:
  CARGO_TERM_COLOR: always
  BINARY_NAME: vim-alchemy

jobs:
  release-linux:
    name: Release - Linux x86_64
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-unknown-linux-gnu
          override: true
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgmp-dev
          
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --verbose --release
          
      - name: Prepare assets
        shell: bash
        run: |
          mkdir -p release/
          cp target/release/${{ env.BINARY_NAME }} release/
          
          # Include additional files
          cp README.md release/ || true
          cp LICENSE* release/ || true
          
          # Create archive
          cd release
          tar -czf ../${{ env.BINARY_NAME }}-Linux-x86_64.tar.gz *
          cd ..
          
      - name: Generate SHA-256 checksums
        shell: bash
        run: |
          sha256sum ${{ env.BINARY_NAME }}-Linux-x86_64.tar.gz > ${{ env.BINARY_NAME }}-Linux-x86_64.sha256
          
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{ env.BINARY_NAME }}-Linux-x86_64.*
          generate_release_notes: true
          prerelease: ${{ github.event.inputs.prerelease || false }}
          tag_name: ${{ github.event.inputs.version || github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
