name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    
    - name: Generate changelog
      id: changelog
      run: |
        # Get the previous tag
        PREV_TAG=$(git describe --tags --abbrev=0 HEAD^ 2>/dev/null || echo "")
        
        if [ -n "$PREV_TAG" ]; then
          # Generate changelog since last tag
          CHANGELOG=$(git log $PREV_TAG..HEAD --pretty=format:"- %s" --no-merges)
        else
          # First release, get all commits
          CHANGELOG=$(git log --pretty=format:"- %s" --no-merges)
        fi
        
        # Save changelog to file
        echo "$CHANGELOG" > CHANGELOG.md
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        draft: false
        prerelease: false
        generate_release_notes: true
        body: |
          ## Changes
          $(cat CHANGELOG.md)
          
          ## Installation
          
          Install with your favorite plugin manager:
          
          ### lazy.nvim
          ```lua
          {
              "rubenduburck/vim-alchemy",
              event = "VeryLazy",
              build = "make install",
              tag = "${{ github.ref_name }}",
          }
          ```
          
          ### packer.nvim
          ```lua
          use {
              'rubenduburck/vim-alchemy',
              tag = '${{ github.ref_name }}',
              run = 'make install'
          }
          ```
          
          The `make install` command will automatically download the latest alchemy binary from https://github.com/rubenduburck/alchemy/releases
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}