name: Release

on:
  push:
    branches: [main]
  release:
    types: [created]

env:
  CARGO_TERM_COLOR: always

jobs:
  check-version:
    name: Check Version Change
    runs-on: ubuntu-latest
    outputs:
      version_changed: ${{ steps.version.outputs.changed }}
      current_version: ${{ steps.version.outputs.current }}
      previous_version: ${{ steps.version.outputs.previous }}
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Check if version changed
      id: version
      run: |
        # Get current version from Cargo.toml
        CURRENT_VERSION=$(grep '^version = ' Cargo.toml | sed 's/version = "\(.*\)"/\1/')
        echo "current=$CURRENT_VERSION" >> $GITHUB_OUTPUT
        
        # Check if tag already exists
        if git tag -l "v$CURRENT_VERSION" | grep -q "v$CURRENT_VERSION"; then
          echo "Tag v$CURRENT_VERSION already exists"
          echo "changed=false" >> $GITHUB_OUTPUT
        else
          echo "New version detected: v$CURRENT_VERSION"
          echo "changed=true" >> $GITHUB_OUTPUT
        fi

  build:
    name: Build ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    needs: check-version
    if: needs.check-version.outputs.version_changed == 'true'
    strategy:
      matrix:
        include:
          # Linux
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
            name: alchemy-x86_64-linux
          - target: aarch64-unknown-linux-gnu
            os: ubuntu-latest
            name: alchemy-aarch64-linux
          
          # macOS
          - target: x86_64-apple-darwin
            os: macos-latest
            name: alchemy-x86_64-macos
          - target: aarch64-apple-darwin
            os: macos-latest
            name: alchemy-aarch64-macos
          
          # Windows
          - target: x86_64-pc-windows-msvc
            os: windows-latest
            name: alchemy-x86_64-windows
            extension: .exe

    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: ${{ matrix.target }}
    
    - name: Install cross-compilation tools (Linux ARM64)
      if: matrix.target == 'aarch64-unknown-linux-gnu'
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-aarch64-linux-gnu
    
    - name: Configure cross-compilation
      if: matrix.target == 'aarch64-unknown-linux-gnu'
      run: |
        mkdir -p ~/.cargo
        echo '[target.aarch64-unknown-linux-gnu]' >> ~/.cargo/config.toml
        echo 'linker = "aarch64-linux-gnu-gcc"' >> ~/.cargo/config.toml
    
    - name: Build
      run: cargo build --release --target ${{ matrix.target }}
    
    - name: Prepare artifact
      shell: bash
      run: |
        cd target/${{ matrix.target }}/release
        if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
          cp alchemy.exe ../../${{ matrix.name }}.exe
        else
          cp alchemy ../../${{ matrix.name }}
        fi
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.name }}
        path: target/${{ matrix.name }}${{ matrix.extension }}

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: [check-version, build]
    if: needs.check-version.outputs.version_changed == 'true'
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts
    
    - name: Generate changelog
      id: changelog
      run: |
        # Get the last tag (if any)
        LAST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "")
        
        if [ -n "$LAST_TAG" ]; then
          # Generate changelog since last tag
          CHANGELOG=$(git log $LAST_TAG..HEAD --pretty=format:"- %s" --no-merges)
        else
          # First release, get recent commits
          CHANGELOG=$(git log --pretty=format:"- %s" --no-merges -10)
        fi
        
        # Save changelog to file for use in release body
        echo "$CHANGELOG" > CHANGELOG.md
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ needs.check-version.outputs.current_version }}
        name: Release v${{ needs.check-version.outputs.current_version }}
        draft: false
        prerelease: false
        generate_release_notes: true
        files: artifacts/*/alchemy*
        body: |
          ## Alchemy v${{ needs.check-version.outputs.current_version }}
          
          ### Changes
          $(cat CHANGELOG.md)
          
          ### Downloads
          Choose the binary for your platform:
          - **Linux x64**: `alchemy-x86_64-linux`
          - **Linux ARM64**: `alchemy-aarch64-linux`
          - **macOS Intel**: `alchemy-x86_64-macos`
          - **macOS Apple Silicon**: `alchemy-aarch64-macos`
          - **Windows x64**: `alchemy-x86_64-windows.exe`
          
          ### Installation
          1. Download the appropriate binary for your platform
          2. Rename it to `alchemy` (remove architecture suffix)
          3. Make it executable: `chmod +x alchemy`
          4. Move to a directory in your PATH: `mv alchemy ~/.local/bin/`
          
          Or use the Neovim plugin with `build = "make install"` to automatically download the correct binary.
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}