name: Build and Release Binary

on:
  push:
    tags:
      - 'v*' # Triggers workflow on version tags like v1.0.0
  workflow_dispatch: # Allows manual triggering

jobs:
  build:
    name: Build Binary
    runs-on: ubuntu-latest

    strategy:
      matrix:
        target: [x86_64-unknown-linux-gnu, x86_64-pc-windows-msvc, x86_64-apple-darwin]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install Dependencies
        run: cargo fetch

      - name: Build Binary
        run: cargo build --release --target ${{ matrix.target }}

      - name: Upload Binary
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.target }}-binary
          path: target/${{ matrix.target }}/release/
  
  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download Binaries
        uses: actions/download-artifact@v3
        with:
          name: x86_64-unknown-linux-gnu-binary
          path: ./binaries/linux

      - name: Download Binaries (Windows)
        uses: actions/download-artifact@v3
        with:
          name: x86_64-pc-windows-msvc-binary
          path: ./binaries/windows

      - name: Download Binaries (Mac)
        uses: actions/download-artifact@v3
        with:
          name: x86_64-apple-darwin-binary
          path: ./binaries/mac

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: |
            ./binaries/linux
            ./binaries/windows
            ./binaries/mac
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            Download the binaries for your platform.
          draft: false
          prerelease: false

